#!/usr/bin/env ruby
require "open3"

def snapshot_version(version, allow_snapshot)
  if allow_snapshot
    "#{version}-SNAPSHOT"
  else
    version
  end
end

def maven_version(allow_snapshot = true)
  output, status = Open3.capture2e("git describe --abbrev=0 --tags")
  return snapshot_version("0.0.1", allow_snapshot) unless status.success?
  match = /\Av(\d.*)$/.match(output)
  return snapshot_version("0.0.1", allow_snapshot) unless match
  version = match[1]
  output, status = Open3.capture2e("git describe --exact-match --tags HEAD")
  return snapshot_version(version, allow_snapshot) unless status.success?
  return snapshot_version(version, allow_snapshot) unless output.strip == "v#{version}"
  return version
end

def update_pom_version
  file = File.expand_path("pom.xml")
  contents = File.read(file)
  abort "#{file} is already versioned!" unless contents.include?("CUSTOM_VERSION")
  version = maven_version
  strict_version = maven_version(false)
  puts "Updating pom to use version: #{version}"
  contents.gsub!("STRICT_CUSTOM_VERSION", strict_version)
  contents.gsub!("CUSTOM_VERSION", version)
  File.write(file, contents)
end

def mvn(command)
  command = "mvn #{command} -B -V --settings '#{File.expand_path("../settings.xml", __FILE__)}'"
  puts "running: #{command}"
  exec command
end

def prep
  update_pom_version
end

def install
  mvn "install -DskipTests=true -Dmaven.javadoc.skip=true"
end

def run
  if maven_version.end_with?("SNAPSHOT")
    puts "Testing snapshot version"
    mvn "test"
  else
    puts "Deploying new version"
    mvn "deploy"
  end
end

def usage
  abort "Usage: ./ci <prep|install|run>"
end

usage if ARGV.size != 1

case ARGV[0]
when "prep"
  prep
when "install"
  install
when "run"
  run
else
  usage
end
