#!/usr/bin/env ruby
require_relative "maven_version"

def update_pom_version
  file = File.expand_path("../pom.xml", __FILE__)
  contents = File.read(file)
  abort "#{file} is already versioned!" unless contents.include?("CUSTOM_VERSION")
  File.write(file, contents.gsub("CUSTOM_VERSION", maven_version))
end

update_pom_version
