#!/usr/bin/env ruby
require "open3"

def version
  output, status = Open3.capture2e("git describe --abbrev=0 --tags")
  return "UNKNOWN-SNAPSHOT" unless status.success?
  match = /\Av(\d.*)$/.match(output)
  return "UNKNOWN-SNAPSHOT" unless match
  version = match[1]
  output, status = Open3.capture2e("git describe --exact-match --tags HEAD")
  return "#{version}-SNAPSHOT" unless status.success?
  return "#{version}-SNAPSHOT" unless output.strip == "v#{version}"
  return version
end

def update_pom_version
  file = File.expand_path("../pom.xml", __FILE__)
  contents = File.read(file)
  abort "#{file} is already versioned!" unless contents.include?("CUSTOM_VERSION")
  File.write(file, contents.gsub("CUSTOM_VERSION", version))
end

update_pom_version
